import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'cli/index': 'src/cli/index.ts',
    index: 'index.ts',
  },
  minify: true,
  bundle: true,
  shims: false,
  splitting: true,
  sourcemap: false,
  treeshake: true,
  clean: true,
  dts: true,
  format: ['cjs', 'esm'],
  target: 'esnext',
  outDir: 'dist',
  platform: 'node',
  tsconfig: 'tsconfig.json',
  external: [
    'fs',
    'path',
    'node:*',
    'reflect-metadata',
    'pino',
    'zod',
    'inversify',
    'citty',
    'jiti',
    'bcrypt',
    'axios',
    'ejs',
    'validator',
    'libphonenumber-js',
    '@nidavellirx/*',
    '@dotenvx/dotenvx',
    'fastify',
    '@fastify/*',
    '@fastify/autoload',
    '@fastify/cookie',
    '@fastify/static',
    '@fastify/view',
    'fastify-ip',
    'fastify-plugin',
  ],
});
