packages:
  - packages/*
  - packages/*/playground

# Save exact versions without ^/~ ranges.
saveExact: true

# Hoist dependencies for tools that expect flat node_modules.
shamefullyHoist: true

# Auto-install resolvable peer dependencies.
autoInstallPeers: true

# Disable pnpm minimum release age checks for this workspace.
minimumReleaseAge: 0

# Do not auto-run install before scripts.
verifyDepsBeforeRun: false

# Fail install on invalid or missing peer dependencies.
strictPeerDependencies: true

peerDependencyRules:
  allowedVersions:
    # Temporary fix
    unbuild@3.6.1>typescript: 6.0.3

    # Temporary fix
    tsconfck@3.1.6>typescript: 6.0.3

    # Temporary fix
    '@nuxt/module-builder@1.0.3>typescript': 6.0.3

    # Temporary fix
    mkdist@2.4.1>vue-sfc-transformer: 0.2.5

overrides:
  # Temporary fix
  '@napi-rs/wasm-runtime@': 1.1.6

allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  argon2: true
  esbuild: true
  nx: true
  sharp: true
  vue-demi: true
