import fs from 'node:fs';
import path from 'node:path';

import { afterAll, describe, expect, test } from 'vitest';

import { cleanupConsumerProjects, createConsumerProject, createModule } from '#test/fixtures/consumer-project';
import { writeFile } from '#test/fixtures/files';
import { runArchicatCommand } from '#test/fixtures/run-archicat-command';

describe('generated output safety', async () => {
  afterAll(() => {
    cleanupConsumerProjects();
  });

  test('should reject outDir outside the project root without deleting it', async () => {
    const root = createConsumerProject('unsafe-outdir', {
      config: { outDir: '../outside' },
    });
    const outsideDir = path.resolve(root, '../outside');
    const sentinelPath = path.join(outsideDir, 'keep.txt');

    createModule(root, { name: 'account' });
    writeFile(sentinelPath, 'keep');

    const result = await runArchicatCommand(root, 'generate');

    expect(result.status).not.toBe(0);
    expect(result.stderr).toMatch(/outDir must be a directory inside the project root/);
    expect(fs.readFileSync(sentinelPath, 'utf8').trim()).toBe('keep');
  });

  test('should replace an output directory previously generated by Archicat', async () => {
    const root = createConsumerProject('owned-outdir');
    const stalePath = path.join(root, '.archicat/stale.txt');

    createModule(root, { name: 'account' });

    const firstResult = await runArchicatCommand(root, 'generate');
    expect(firstResult.status, firstResult.stderr).toBe(0);

    writeFile(stalePath, 'stale');

    const secondResult = await runArchicatCommand(root, 'generate');

    expect(secondResult.status, secondResult.stderr).toBe(0);
    expect(fs.existsSync(stalePath)).toBe(false);
  });

  test('should refuse to replace an existing directory not owned by Archicat', async () => {
    const root = createConsumerProject('non-owned-outdir', {
      config: { outDir: './generated' },
    });
    const generatedDir = path.join(root, 'generated');
    const sentinelPath = path.join(generatedDir, 'keep.txt');

    createModule(root, { name: 'account' });
    writeFile(sentinelPath, 'keep');

    const result = await runArchicatCommand(root, 'generate');

    expect(result.status).not.toBe(0);
    expect(result.stderr).toMatch(/refuses to replace a non-owned outDir/);
    expect(fs.readFileSync(sentinelPath, 'utf8').trim()).toBe('keep');
  });

  test('should reject an Archicat report that belongs to a different outDir', async () => {
    const root = createConsumerProject('mismatched-owned-outdir', {
      config: { outDir: './generated' },
    });
    const generatedDir = path.join(root, 'generated');
    const sentinelPath = path.join(generatedDir, 'keep.txt');

    createModule(root, { name: 'account' });
    writeFile(sentinelPath, 'keep');
    writeFile(
      path.join(generatedDir, 'reports/build.report.json'),
      JSON.stringify({
        generatedBy: 'archicat',
        schemaVersion: 2,
        outputs: { outDir: '.archicat' },
      }),
    );

    const result = await runArchicatCommand(root, 'generate');

    expect(result.status).not.toBe(0);
    expect(result.stderr).toMatch(/refuses to replace a non-owned outDir/);
    expect(fs.readFileSync(sentinelPath, 'utf8').trim()).toBe('keep');
  });

  test('should reject outDir that escapes through a symlink', async () => {
    const root = createConsumerProject('unsafe-symlink-outdir', {
      config: { outDir: './generated/output' },
    });
    const outsideDir = path.resolve(root, '../symlink-target');
    const generatedLink = path.join(root, 'generated');
    const sentinelPath = path.join(outsideDir, 'keep.txt');

    createModule(root, { name: 'account' });
    fs.mkdirSync(outsideDir, { recursive: true });
    writeFile(sentinelPath, 'keep');
    fs.symlinkSync(outsideDir, generatedLink, 'dir');

    const result = await runArchicatCommand(root, 'generate');

    expect(result.status).not.toBe(0);
    expect(result.stderr).toMatch(/outDir must be a directory inside the project root/);
    expect(fs.readFileSync(sentinelPath, 'utf8').trim()).toBe('keep');
  });
});
