import fs from 'node:fs';
import path from 'node:path';

import { afterAll, describe, expect, test } from 'vitest';

import { writeFile } from '#test/fixtures/files';
import { runCommand } from '#test/fixtures/run-command';
import { cleanupTestProjects, createModule, createTestProject } from '#test/fixtures/test-project';

describe('generated output safety', () => {
  afterAll(cleanupTestProjects);

  test('never deletes an outDir outside the project root', async () => {
    const root = createTestProject('outside', { config: { outDir: '../outside' } });
    const outside = path.resolve(root, '../outside');
    const sentinel = path.join(outside, 'keep.txt');

    createModule(root, { name: 'dummy' });
    writeFile(sentinel, 'keep');

    const result = await runCommand(root, 'generate');
    expect(result.status).not.toBe(0);
    expect(result.output).toMatch(/outDir must be a directory inside the project root/);
    expect(fs.readFileSync(sentinel, 'utf8').trim()).toBe('keep');
  });

  test('replaces only output previously generated by Archicat', async () => {
    const root = createTestProject('owned');
    const stale = path.join(root, '.archicat/stale.txt');

    createModule(root, { name: 'dummy' });

    const first = await runCommand(root, 'generate');
    expect(first.status, first.output).toBe(0);

    writeFile(stale, 'stale');

    const second = await runCommand(root, 'generate');
    expect(second.status, second.output).toBe(0);
    expect(fs.existsSync(stale)).toBe(false);
  });

  test('refuses to replace an unowned output directory', async () => {
    const root = createTestProject('unowned', { config: { outDir: './generated' } });
    const sentinel = path.join(root, 'generated/keep.txt');

    createModule(root, { name: 'dummy' });
    writeFile(sentinel, 'keep');

    const result = await runCommand(root, 'generate');
    expect(result.status).not.toBe(0);
    expect(result.output).toMatch(/refuses to replace a non-owned outDir/);
    expect(fs.readFileSync(sentinel, 'utf8').trim()).toBe('keep');
  });

  test('rejects an ownership report for another outDir', async () => {
    const root = createTestProject('wrong-owner', { config: { outDir: './generated' } });
    const sentinel = path.join(root, 'generated/keep.txt');

    createModule(root, { name: 'dummy' });
    writeFile(sentinel, 'keep');
    writeFile(
      path.join(root, 'generated/reports/build.report.json'),
      JSON.stringify({
        generatedBy: 'archicat',
        schemaVersion: 2,
        outputs: { outDir: '.archicat' },
      }),
    );

    const result = await runCommand(root, 'generate');
    expect(result.status).not.toBe(0);
    expect(result.output).toMatch(/refuses to replace a non-owned outDir/);
    expect(fs.readFileSync(sentinel, 'utf8').trim()).toBe('keep');
  });

  test('rejects an outDir that escapes through a symlink', async () => {
    const root = createTestProject('symlink', { config: { outDir: './generated/output' } });
    const outside = path.resolve(root, '../symlink-target');
    const link = path.join(root, 'generated');
    const sentinel = path.join(outside, 'keep.txt');

    createModule(root, { name: 'dummy' });
    fs.mkdirSync(outside, { recursive: true });
    writeFile(sentinel, 'keep');
    fs.symlinkSync(outside, link, 'dir');

    const result = await runCommand(root, 'generate');
    expect(result.status).not.toBe(0);
    expect(result.output).toMatch(/outDir must be a directory inside the project root/);
    expect(fs.readFileSync(sentinel, 'utf8').trim()).toBe('keep');
  });
});
