/**
 * @description TypeScript config fragment merged into generated `.archicat/tsconfig.json`.
 */
export interface TsConfigInput {
  /**
   * @description Base TypeScript config extended by generated `.archicat/tsconfig.json`.
   */
  readonly extends?: string;

  /**
   * @description Project source files merged into generated `.archicat/tsconfig.json` include.
   * Archicat rewrites relative paths to the generated config directory and appends generated type declarations automatically.
   */
  readonly include?: readonly string[];

  /**
   * @description Project paths merged into generated `.archicat/tsconfig.json` exclude.
   * Archicat rewrites relative paths to the generated config directory.
   */
  readonly exclude?: readonly string[];

  /**
   * @description Project files merged into generated `.archicat/tsconfig.json` files.
   * Archicat rewrites relative paths to the generated config directory.
   */
  readonly files?: readonly string[];

  /**
   * @description Unsupported. Put compiler options in the base or app tsconfig. Archicat owns generated `compilerOptions.paths` and does not support `baseUrl`.
   */
  readonly compilerOptions?: {
    readonly paths?: never;
    readonly baseUrl?: never;
  };
}

/**
 * @description TypeScript integration options used to generate `.archicat/tsconfig.json`.
 */
export interface TypeScriptConfigInput {
  /**
   * @description Partial TypeScript config merged into generated `.archicat/tsconfig.json`.
   * Archicat rewrites relative paths from the project root to `.archicat`, appends generated type declarations to `include`, and injects generated aliases into `compilerOptions.paths`.
   * `compilerOptions` is not supported here. Put compiler policy in the base tsconfig and app build overrides in the app tsconfig.
   * @default {}
   */
  readonly tsConfig?: TsConfigInput;
}

/**
 * @description User import aliases generated into `.archicat/tsconfig.json` together with Archicat module and library aliases.
 * Aliases are resolved relative to the Archicat project root. Do not define TypeScript `compilerOptions.paths` manually for an Archicat project.
 * @default {}
 */
export type AliasConfig = Readonly<Record<string, string>>;

/**
 * @description Module discovery and generated import alias configuration.
 */
export interface ModulesConfigInput {
  /**
   * @description Directories or files where Archicat searches for module definition markers.
   */
  readonly include?: readonly string[];

  /**
   * @description Base alias used for generated module imports.
   */
  readonly alias?: string;
}

/**
 * @description Library discovery and generated import alias configuration.
 */
export interface LibrariesConfigInput {
  /**
   * @description Directories or files where Archicat searches for library definition markers.
   */
  readonly include?: readonly string[];

  /**
   * @description Base alias used for generated library imports.
   */
  readonly alias?: string;
}

/**
 * @description App discovery configuration.
 */
export interface AppsConfigInput {
  /**
   * @description Directories or files where Archicat searches for app definition markers.
   */
  readonly include?: readonly string[];
}

/**
 * @description User-facing Archicat root config input.
 */
export interface ArchicatConfigInput {
  /**
   * @description Project root directory.
   * @default '.'
   */
  readonly root?: string;

  /**
   * @description Directory for generated mirror files, generated types, and reports.
   * @default '.archicat'
   */
  readonly outDir?: string;

  /**
   * @description TypeScript integration options used to generate `.archicat/tsconfig.json`.
   * @default {}
   */
  readonly typescript?: TypeScriptConfigInput;

  /**
   * @description User TypeScript aliases generated by Archicat.
   * @default {}
   */
  readonly alias?: AliasConfig;

  /**
   * @description Module discovery and alias config.
   * @default { include: ['./src/modules'], alias: '#modules' }
   */
  readonly modules?: ModulesConfigInput;

  /**
   * @description Library discovery and alias config.
   * @default { include: [], alias: '#library' }
   */
  readonly libraries?: LibrariesConfigInput;

  /**
   * @description App discovery config.
   * @default { include: [] }
   */
  readonly apps?: AppsConfigInput;
}

/**
 * @description Immutable Archicat config returned by `defineArchicatConfig`.
 */
export type ArchicatConfig = Readonly<ArchicatConfigInput>;
