name: Publish Packages

on:
  workflow_dispatch: {} # Manual Trigger Only

jobs:
  publish:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [24]

    permissions:
      contents: write
      packages: write

    steps:
      # MARK: - Checkout
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # MARK: - Setup PNPM
      - name: Install pnpm
        uses: pnpm/action-setup@v5

      # MARK: - Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com
          cache: pnpm

      # MARK: - Install Dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # MARK: - Build Packages
      - name: Build packages
        run: pnpm run build

      # MARK: - Publish (Lerna)
      - name: Publish packages
        run: npx lerna publish from-package --yes --summary-file ./lerna-publish-summary.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # MARK: - Git Tags
      - name: Create git tags
        run: |
          SUMMARY_FILE="./lerna-publish-summary.json"

          if [ ! -f "$SUMMARY_FILE" ]; then
            exit 0
          fi

          PACKAGES=$(jq -r '.[] | "\(.packageName)@\(.version)"' "$SUMMARY_FILE")

          for PACKAGE in $PACKAGES; do
            if git rev-parse "$PACKAGE" >/dev/null 2>&1; then
              continue
            fi

            git tag "$PACKAGE"
          done

          git push --tags
