name: Publish Packages

on:
  workflow_dispatch: # Manual Trigger Only

jobs:
  publish:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    permissions:
      contents: write
      packages: write

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup PNPM
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'

      # Install Dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build All Packages
      - name: Build Packages
        run: pnpm run build

      # Publish Updated Packages Using Lerna
      - name: Publish with Lerna 🚀
        run: npx lerna publish from-package --yes --summary-file ./lerna-publish-summary.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Parse Summary and Generate Git Tags
      - name: Generate Git Tags for Published Packages 🏷️
        run: |
          # Parse JSON and create tags
          SUMMARY_FILE="./lerna-publish-summary.json"
          if [ -f "$SUMMARY_FILE" ]; then
            PACKAGES=$(jq -r '.[] | "\(.packageName)@\(.version)"' $SUMMARY_FILE)

            # Loop through packages and create Git tags
            for PACKAGE in $PACKAGES; do
              echo "Tagging $PACKAGE..."
              git tag "$PACKAGE"
            done

            # Push all tags to the remote repository
            git push --tags
          else
            echo "No summary file found. Skipping tag creation."
          fi
